app = "thingsboard-demo"

[build]
  dockerfile = "Dockerfile.flyio"

[env]
  TB_QUEUE_TYPE = "in-memory"
  JAVA_OPTS = "-Xms128m -Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxRAM=600m"
  TB_LOAD_DEMO = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[services]]
  protocol = "tcp"
  internal_port = 1883
  processes = ["app"]

  [[services.ports]]
    port = 1883

[[services]]
  protocol = "udp"
  internal_port = 5683
  processes = ["app"]

  [[services.ports]]
    port = 5683 